apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp3
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myapp3
  template:
    metadata:
      labels:
        app: myapp3
    spec:
      volumes:
        - name: my-pv
          persistentVolumeClaim:
            claimName: my-pvc
      containers:
        - name: myapp3
          image: k8simg:v6
          resources:
            requests:
              memory: "128Mi"
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: my-pv
              mountPath: /data
          ports:
            - containerPort: 5001
          env:
            - name: KV_FILE_PATH
              value: /data
            - name: SYNC_WHEN_NOT_FOUND
              value: 'false'
            - name: JOB_FREQUENCY_IN_SECONDS
              value: '1'
