apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp3
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myapp3
  template:
    metadata:
      labels:
        app: myapp3
    spec:
      containers:
        - name: myapp3
          image: k8simg:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 5001
