apiVersion: v1
kind: Service
metadata:
  name: myapp3
  labels:
    run: myapp3

spec:
  type: NodePort
  ports:
    - port: 5001
      targetPort: 5001
      protocol: TCP
  selector:
    app: myapp3